services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexus_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - nexus_network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: nexus_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nexus_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nexus_network

  redis:
    image: redis:alpine
    container_name: nexus_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - nexus_network

  queue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexus_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --sleep=3 --tries=3
    volumes:
      - ./backend:/var/www
    networks:
      - nexus_network
    depends_on:
      - app
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexus_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - nexus_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: nexus_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - nexus_network

networks:
  nexus_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
